### PR TITLE
First version of French version. Version.

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Here we are!

I took time to translate the new section about specificity this afternoon. Everything should be okay by now.

### CODE REVIEW

**Comment by flexbox** [comment]
Hello @HugoGiraudel 
That's amazing i have just refactor a french version http://guidecss.fr/ ^^

**Comment by KittyGiraudel** [comment]
Refactor? What do you mean?

**Comment by flexbox** [comment]
I have push a french version online
But i haven't see http://cssguidelin.es/ and your translation job -_-

**Comment by KittyGiraudel** [comment]
Your version doesn't seem like a translation from Harry's work. Or is it?

**Comment by flexbox** [comment]
It's an old one...
I think your version i more updated.
When are you sleeping guys ?

2014-09-29 18:25 GMT+02:00 Hugo Giraudel notifications@github.com:

> Your version doesn't seem like a translation from Harry's work. Or is it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csswizardry/CSS-Guidelines/pull/31#issuecomment-57187271
> .

## 

David Leuliette
Front-end Developer http://davidl.fr

**Comment by csswizardry** [comment]
@HugoGiraudel It’s an as-yet uncredited version of the 1.0.0 Guidelines: https://github.com/csswizardry/CSS-Guidelines/blob/be20df6dc00a05ccabe48f8511e402f8bcd5aedb/README.md

**Comment by florianbouvot** [comment]
@flexbox I think your version don't respect @csswizardry's work. I remember that first time I looked at your website, I say "Oh it looks nice", but after 5 minutes I say "I've read that somewhere". Not to mention @csswizardry at the beginning is misleading.

**Comment by flexbox** [comment]
Its in the human.txt but i am going to change it & put directly in the footer 

/***************************/
-    David Leuliette 
-    Front-end developer
-    http://davidl.fr
  /***************************/

**Comment by KittyGiraudel** [comment]
@pierrechoffe did some massive improvements to my initial translation. Please be sure to credit him as well.

**Pull request closed without merging**
